---
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: check-merge-conflict
      - id: check-case-conflict
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.10
    hooks:
      - id: remove-crlf
      - id: remove-tabs
  - repo: https://github.com/gitguardian/gg-shield
    rev: v1.8.1
    hooks:
      - id: ggshield
        language_version: python3
        stages: [commit]
