--- 
prometheusRule:
  enabled: true
  additionalLabels: {}
  namespace: ""
  rules:
    ## These are just examples rules, please adapt them to your needs.
    ## Make sure to constraint the rules to the current prometheus-dnssec-exporter service.
    - alert: DNSSECSignatureExpiration
      expr: dnssec_zone_record_days_left{service="{{ template "prometheus-dnssec-exporter.fullname" . }}"} < 10
      for: 1m
      labels:
        severity: warning
      annotations:
        description: |
           The DNSSEC signature for the {{ "{{ $labels.record }}" }} in {{ "{{ $labels.zone }}" }}
           type {{ "{{ $labels.type }}" }} expires in {{ "{{ $value }}" }} day(s)
        summary: |
          The DNSSEC signature for the {{ "{{ $labels.record }}" }} in {{ "{{ $labels.zone }}" }} is expiring
    - alert: DNSSECSignatureInvalid
      expr: dnssec_zone_record_resolves{service="{{ template "prometheus-dnssec-exporter.fullname" . }}"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        description: |
          The DNSSEC signature for the {{ "{{ $labels.record }}" }} in {{ "{{ $labels.zone }}" }}
          type {{ "{{ $labels.type }}" }} on resolver {{ "{{ $labels.resolver }}" }} is invalid
        sumary: |
          The DNSSEC signature for the {{ "{{ $labels.record }}" }} in {{ "{{ $labels.zone }}" }}
          on resolver {{ "{{ $labels.resolver }}" }} is invalid
