name: "Run Lint and Helm Tests"
description: "Run Lint and Helm Tests"

runs:
  using: "composite"
  steps:
    - name: Set up Helm
      uses: azure/setup-helm@v1

    - uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2.1.0

    - name: Run chart-testing (list-changed)
      id: list-changed
      run: |
        changed=$(ct list-changed --config .github/ct-lint.yaml)
        if [[ -n "$changed" ]]; then
          echo "::set-output name=changed::true"
        fi
      shell: bash

    - name: Run chart-testing (lint)
      run: ct lint --all --config .github/ct-lint.yaml
      shell: bash

    - name: Create kind cluster
      uses: helm/kind-action@v1.2.0
#      if: steps.list-changed.outputs.changed == 'true'

    - name: Run chart-testing (install)
      run: ct install --config .github/ct-lint.yaml
      shell: bash
