name: Lint and Test Charts

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - main
    paths:
    - 'charts/**'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint and Test
        uses: ./.github/actions/lint-test-action
